### ISSUE TITLE
What's the connect URL for the App?

### ISSUE THREAD

**Issue by pythonInRelay** [jellyfin/jellyfin-uwp#19]
I have Jellyfin running on my server at 192.168.1.50:8096 but my Xbox keeps saying that my server is off when trying this address. What URL am I supposed to enter?

**Comment by Clickbaitcake** [comment]
Try prefixing with http://
`http://192.168.1.50:8096`

**Comment by pythonInRelay** [comment]
> 
> 
> Try prefixing with http://
> `http://192.168.1.50:8096`
> 
> A fix for your issue is being tracked here: #15

Wow, that fixed it. It should either be added by default or there should be a mention that it's required. Thanks though! It connected!

**Comment by Clickbaitcake** [comment]
> > Try prefixing with http://
> > `http://192.168.1.50:8096`
> > A fix for your issue is being tracked here: #15
> 
> Wow, that fixed it. It should either be added by default or there should be a mention that it's required. Thanks though! It connected!

The other issue I linked to describes an exact fix for this problem, it’s implemented just waiting for release. Click the link and have a read.
