### ISSUE TITLE
Current build not working with Jellyfin 10.6.0

### ISSUE THREAD

**Issue by Feral2k** [jellyfin/jellyfin-uwp#24]
As @anthonylavado [mentioned](https://github.com/jellyfin/jellyfin-uwp/issues/22#issuecomment-663040058). the current build is not working with the Jellyfin server as of version 10.6.0. I thought this was significant enough to be a dedicated issue instead of being mentioned in a comment within another issue.

As a temporary work-around, apart from using the web version of Jellyfin from the Edge browser, there is an app for Xbox and Windows devices called [Videotape](https://www.microsoft.com/en-us/p/videotape-a-modern-vlc-alternative/9nlvh2ll4p1z?activetab=pivot:overviewtab) that works with the most recent version of the server and looks pretty nice.

**Comment by PrayagPrajapati** [comment]
This build is able to connect and direct play HEVC and 4k files from Jellyfin server 10.6.X but there is a small custom CSS issue. To use your Jellyfin server 10.6.X use this formate- http:/youripaddress:portnumber

**Comment by anthonylavado** [comment]
Yeah, we were able to restore access by resolving an MS Edge detection issue, but we still reccommend Videotape going forward.
