### ISSUE TITLE
Client abandoned?

### ISSUE THREAD

**Issue by M0ssTee** [jellyfin/jellyfin-uwp#25]
Is further development planned for this client?  I was disappointed to see the lack of a Jellyfin app in the Microsoft Store; I was hoping to use my Xbox as a client device.  Using the web client in the browser(on the Xbox) leaves large black bars vertically and horizontally around the video, and it would be more convenient to use an app.  I am willing to help however I can, although I am not experienced with C# and UWP.

**Comment by sshirley** [comment]
I'd also like to know the current status of this. I am not experienced with UWP but I do know C# and .NET. Why was this pulled from the Microsoft store? What is there actually to do at this point?

**Comment by joshuaboniface** [comment]
I believe the client was abandoned yes because we had no one who:

(a) had an XBox and interest in using the client; and
(b) who was willing and able to develop it further.

Until we find someone who can satisfy those two it's dead in the water, but if you are interested we'd gladly welcome the help. I'm not sure what state the client is in though, or what the last activity was; the commit history might shed light and feel free to ping anyone who worked on it in the past. You can also join us on Matrix (#jellyfin-dev:matrix.org) to see if anyone knows!

**Comment by Protektor-Desura** [comment]
Last I heard when the server was updated the client stopped being able to login. I believe someone posted that they got that fixed but not idea if they ever submitted a patch or not.

https://www.reddit.com/r/jellyfin/comments/r1dvz1/jellyfin_for_xbox_uwp_required_work/

**Comment by anthonylavado** [comment]
I'll release an update but it's way lower priority at the moment. There's no active developers for this as well, so it's not great.

**Comment by matthewstrasiotto** [comment]
Looks like https://github.com/jellyfin/jellyfin-uwp/issues/25#issuecomment-1031663922 was resolved by #26 

Also, from @anthonylavado 

> I'll release an update but it's way lower priority at the moment. There's no active developers for this as well, so it's not great.

Do you mean you'll re-publish it to the UWP store?

**Comment by anthonylavado** [comment]
@matthewstrasiotto That's the plan, after the webOS app for LG TVs.

**Comment by AstieLuv** [comment]
Any chance the client could be re-published? It seems that everything has been resolved and things are hanging on [#27](https://github.com/jellyfin/jellyfin-uwp/pull/27)

**Comment by Protektor-Desura** [comment]
> @matthewstrasiotto That's the plan, after the webOS app for LG TVs.

Well WebOS app is in the store now. Is this client now on your list of TO-DO?

**Comment by AstieLuv** [comment]
@anthonylavado Are you able to re-publish the app to the store? It seems a waste that all the code is seemingly here but the app is inaccessible to the public, and as much as Edge somewhat works on Xbox, it's lacklustre at best.

**Comment by anthonylavado** [comment]
It is on the list, please hold a little bit more (about a week out)

**Comment by Killerherts** [comment]
> @anthonylavado Are you able to re-publish the app to the store? It seems a waste that all the code is seemingly here but the app is inaccessible to the public, and as much as Edge somewhat works on Xbox, it's lacklustre at best.

Currently navigation is broken I have a fork branch that switches it to mouse control everything seems to function. 
Direct play is only supported up to bitrate of 12.4.

**Comment by anthonylavado** [comment]
@Killerherts If you've got that in your branch, I'll happily accept the fix in a Pull Request 😄

**Comment by CyberaxAnnon** [comment]
Any update regarding this fork?

**Comment by Killerherts** [comment]
> Any update regarding this fork

There is not much to update it just a web wrapper a native client needs to be made I have worked on some stuff but have not had enough time to dedicate.
