### ISSUE TITLE
WebView2  update

### ISSUE THREAD

**Issue by Killerherts** [jellyfin/jellyfin-uwp#32]
I have recreated the url input logic and adapted the controls for WebView2 

https://github.com/Killerherts/jellyfin-webView2

I want to work on getting it navigable by the game pad. But the stage I am at right now already improves video playback and quality for the player. 

I wanted to make sure I posted here and asked for opinions before I submitted a pr for it, as I started from scratch just reusing some assets.

**Comment by XandaPanda42** [comment]
I'm not certain that this project is still managed. Have you heard back from anyone about this? I'm new to git but I came here for the same reason.

**Comment by XandaPanda42** [comment]
The above link isn't working for me. I've had a quick look and I cant see the project in your account either. (New here though, so might have just missed it.)

**Comment by Killerherts** [comment]
> The above link isn't working for me. I've had a quick look and I cant see the project in your account either. (New here though, so might have just missed it.)

I have been the only contributor for several years. Sorry it was late, I forgot to flip the public switch. The link should work now

**Comment by Killerherts** [comment]
I just pushed a working 0.1 version to the master.

**Comment by Killerherts** [comment]
Pushed pr to uwp-rewrite branch
