### ISSUE TITLE
unable to connect to https - only server.

### ISSUE THREAD

**Issue by Betonhaus** [jellyfin/jellyfin-uwp#38]
Hi, my server has a domain name (mysite).tplinkdns.com/jellyfin with a signed certificate and I'm unable to connect to it. I enter https://(mysite).tplinkdns.com/jellyfin (as i would for the web clients) and i get the error message "We're unable to connect to the selected server right now. Please ensure it is running and try again"

My server is Debian 12 and Jellyfin is installed as part of Swizzin, so the root url is /jellyfin and I have a letsencrypt certificate.

**Comment by Killerherts** [comment]
https://.tplinkdns.com/jellyfin should prob be 
https://tplinkdns.com/jellyfin
Also we are in the middle of a roll back I don't believe has gone live make sure your application is updated.

**Comment by Betonhaus** [comment]
Corrected the typo, I used angle brackets which were interpreted as html tags

**Comment by AncientMystic** [comment]
I am also having this issue (with the rollback) I reinstalled it and now cannot connect to a local http server via ip at all

**Comment by Killerherts** [comment]
@AncientMystic pr #41 will fix this issue you can use edge in the meantime you could also help me out by doing a pull and testing funcationality

**Comment by AncientMystic** [comment]
> @AncientMystic pr #41 will fix this issue you can use edge in the meantime you could also help me out by doing a pull and testing functionality.
> 
> I have tested it on windows, xbox one, and xbox x with two different servers.

I really don’t have any experience doing pull requests on GitHub but i can give a try here next week if the issue is still ongoing. 

Last i tested it i still could not get it to connect to the server just using the basic http/lan ip to connect and this is the only app that fails to connect 

i am using an Xbox one X

**Comment by Killerherts** [comment]
> > @AncientMystic pr #41 will fix this issue you can use edge in the meantime you could also help me out by doing a pull and testing functionality.
> > I have tested it on windows, xbox one, and xbox x with two different servers.
> 
> I really don’t have any experience doing pull requests on GitHub but i can give a try here next week if the issue is still ongoing.
> 
> Last i tested it i still could not get it to connect to the server just using the basic http/lan ip to connect and this is the only app that fails to connect
> 
> i am using an Xbox one X

No worries man I have tested the #41 update. Anthony is going to bail us out when he has time as far as the merge conflicts go. It's a bit above my level of git and source control. 
It should sort out soon if you want to rest the PR you can on my recover branch from the PR you will need you Xbox x in dev kit mode inorder to do that.

**Comment by AncientMystic** [comment]
> > > @AncientMystic pr #41 will fix this issue you can use edge in the meantime you could also help me out by doing a pull and testing functionality.
> > > I have tested it on windows, xbox one, and xbox x with two different servers.
> > 
> > 
> > I really don’t have any experience doing pull requests on GitHub but i can give a try here next week if the issue is still ongoing.
> > Last i tested it i still could not get it to connect to the server just using the basic http/lan ip to connect and this is the only app that fails to connect
> > i am using an Xbox one X
> 
> No worries man I have tested the #41 update. Anthony is going to bail us out when he has time as far as the merge conflicts go. It's a bit above my level of git and source control. It should sort out soon if you want to rest the PR you can on my recover branch from the PR you will need you Xbox x in dev kit mode inorder to do that.

That is good to hear and i will test the app as soon as i am able to and report back, i do not have dev mode though on my xbox, just got it for free as someone was getting rid of it after upgrading haven't really used it as anything more than a jellyfin client and will probably replace it soon as i never have really liked consoles, forced updates or the software restrictions. If only it would run linux haha

**Comment by Killerherts** [comment]
> > > > @AncientMystic pr #41 will fix this issue you can use edge in the meantime you could also help me out by doing a pull and testing functionality.
> > > > I have tested it on windows, xbox one, and xbox x with two different servers.
> > > 
> > > 
> > > I really don’t have any experience doing pull requests on GitHub but i can give a try here next week if the issue is still ongoing.
> > > Last i tested it i still could not get it to connect to the server just using the basic http/lan ip to connect and this is the only app that fails to connect
> > > i am using an Xbox one X
> > 
> > 
> > No worries man I have tested the #41 update. Anthony is going to bail us out when he has time as far as the merge conflicts go. It's a bit above my level of git and source control. It should sort out soon if you want to rest the PR you can on my recover branch from the PR you will need you Xbox x in dev kit mode inorder to do that.
> 
> That is good to hear and i will test the app as soon as i am able to and report back, i do not have dev mode though on my xbox, just got it for free as someone was getting rid of it after upgrading haven't really used it as anything more than a jellyfin client and will probably replace it soon as i never have really liked consoles, forced updates or the software restrictions. If only it would run linux haha

there is a jellyfin media player for linux https://github.com/jellyfin/jellyfin-media-player/releases

xbox is wierd as you have to side load the test builds you also have to sign up for the ability to use your home console as a dev kit and when in that mode its sandboxed so its a pain in the ass to test due to this as you can't use your console as normal i just resorted to having a second xbox and trying to use it in my spare time.

**Comment by Killerherts** [comment]
Issue should be resolved with recent update please uninstall and reinstall the app thank you for your patience 

Please close issue

**Comment by Betonhaus** [comment]
> Issue should be resolved with recent update please uninstall and reinstall the app thank you for your patience
> 
> Please close issue

I see that, thank you. It looks like the app uses a virtual mouse to move and not the directional pad so i won't be using it after all.
