### ISSUE TITLE
Jellyfin clients listing

### ISSUE THREAD

**Issue by Clickbaitcake** [jellyfin/jellyfin-uwp#7]
I think the links on [Jellyfin.org](https://jellyfin.org/docs/general/clients/index.html) should be udated to point to this new repo instead of [chaosinnovator](https://github.com/chaosinnovator/jellyfin-uwp/issues). Do you agree?

**Comment by anthonylavado** [comment]
We'll get this covered, don't worry ;)

**Comment by Artiume** [comment]
This can be closed

**Comment by anthonylavado** [comment]
@Alcatraz077 Because I haven't put this in the server repository yet, do you agree to the license here? https://github.com/jellyfin/jellyfin-docs/issues/308

**Comment by Alcatraz077** [comment]
I'm assuming this is similar to the license that's used by most Linux
distros, so essentially it's free, I own nothing, and whatever I write can
be edited and redistributed?
